# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_app', '0002_auto_20170315_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvp',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
