# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:34
from __future__ import unicode_literals

from django.db import migrations

import csv


def load_data_from_csv(apps, schema_editor):
    # We can't import the Mvp model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    filename = "Last_20_NBA_Finals_MVP_Stat_Sheet.csv"
    Mvp = apps.get_model("stat_app", "Mvp")
    with open(filename, "r") as f:
        fields = {"fieldnames": ("year", "name", "position",
        "team", "age", "school", "points", "rebounds",
        "assists", "steals", "blocks", "shooting_percentage",
        "three_point_percentage", "free_throw_percentage")}
        reader = csv.DictReader(f, **fields)
        for row in reader:
            m = Mvp(**row)
            m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stat_app', '0003_auto_20170315_1430'),
    ]

    operations = [
            migrations.RunPython(load_data_from_csv)
    ]
