print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("<title>This kinda sucks</title>")
print("</head>")
print("<body>")
print(input("What would you like your web page to say?"))
print("</body>")
print("</html>")
